# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetupDevice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SetupDevice.proto',
  package='tsumaki',
  syntax='proto3',
  serialized_pb=_b('\n\x11SetupDevice.proto\x12\x07tsumaki\"?\n\x06\x44\x65vice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0c\x65xperimental\x18\x03 \x01(\x08\".\n\x12SetupDeviceRequest\x12\x18\n\x10target_device_id\x18\x01 \x01(\t\"j\n\x13SetupDeviceResponse\x12\'\n\x0e\x63urrent_device\x18\x01 \x01(\x0b\x32\x0f.tsumaki.Device\x12*\n\x11\x61vailable_devices\x18\x02 \x03(\x0b\x32\x0f.tsumaki.Device2^\n\x12SetupDeviceService\x12H\n\x0bSetupDevice\x12\x1b.tsumaki.SetupDeviceRequest\x1a\x1c.tsumaki.SetupDeviceResponseB\x02H\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='tsumaki.Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tsumaki.Device.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='tsumaki.Device.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='experimental', full_name='tsumaki.Device.experimental', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=93,
)


_SETUPDEVICEREQUEST = _descriptor.Descriptor(
  name='SetupDeviceRequest',
  full_name='tsumaki.SetupDeviceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_device_id', full_name='tsumaki.SetupDeviceRequest.target_device_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=141,
)


_SETUPDEVICERESPONSE = _descriptor.Descriptor(
  name='SetupDeviceResponse',
  full_name='tsumaki.SetupDeviceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_device', full_name='tsumaki.SetupDeviceResponse.current_device', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='available_devices', full_name='tsumaki.SetupDeviceResponse.available_devices', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=249,
)

_SETUPDEVICERESPONSE.fields_by_name['current_device'].message_type = _DEVICE
_SETUPDEVICERESPONSE.fields_by_name['available_devices'].message_type = _DEVICE
DESCRIPTOR.message_types_by_name['Device'] = _DEVICE
DESCRIPTOR.message_types_by_name['SetupDeviceRequest'] = _SETUPDEVICEREQUEST
DESCRIPTOR.message_types_by_name['SetupDeviceResponse'] = _SETUPDEVICERESPONSE

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), dict(
  DESCRIPTOR = _DEVICE,
  __module__ = 'SetupDevice_pb2'
  # @@protoc_insertion_point(class_scope:tsumaki.Device)
  ))
_sym_db.RegisterMessage(Device)

SetupDeviceRequest = _reflection.GeneratedProtocolMessageType('SetupDeviceRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETUPDEVICEREQUEST,
  __module__ = 'SetupDevice_pb2'
  # @@protoc_insertion_point(class_scope:tsumaki.SetupDeviceRequest)
  ))
_sym_db.RegisterMessage(SetupDeviceRequest)

SetupDeviceResponse = _reflection.GeneratedProtocolMessageType('SetupDeviceResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETUPDEVICERESPONSE,
  __module__ = 'SetupDevice_pb2'
  # @@protoc_insertion_point(class_scope:tsumaki.SetupDeviceResponse)
  ))
_sym_db.RegisterMessage(SetupDeviceResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
# @@protoc_insertion_point(module_scope)
